version: "3.9"
services:
  web: 
    image: ksgi/geocoder-platform-web:latest
    ports:
      - "7001:8000"
    depends_on:
      - "db"
    container_name: geocoder-platform-web
  db:
    image: ksgi/geocoder-platform-db:latest
    environment:
      - POSTGRES_USER=census
      - POSTGRES_PASSWORD=census
    shm_size: 1gb
    container_name: geocoder-platform-db
